// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lpvwyczyjriesvfxavil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxwdnd5Y3p5anJpZXN2ZnhhdmlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3ODkwMDMsImV4cCI6MjA3ODM2NTAwM30.j5yHt_FLtc2vef_n0ESwXr-1KKJVln1gCB0vuw5-7Uw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);