// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://yhvhjhtzlgttnjwtvqre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlodmhqaHR6bGd0dG5qd3R2cXJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwMjczMzAsImV4cCI6MjA3NzYwMzMzMH0.EsBpB_4Ml6671WZ3uVq3v-d4uCHxsHCn8MMlXkU8JQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);